### ISSUE TITLE
How to set Keep Alive Timeout: GCP kubernetes Load Balancer 502 issue

### ISSUE THREAD

**Issue by arturictus** [ninenines/cowboy#1286]
Hi,
How can set a keep alive timeout?
I've been checking the documentation and the code and I couldn't find anything.
My case:
We are deploying to Google Cloud with kubernetes. and we are getting random 502 responses because the GCP´s Load Balancer tries so keep connections open and looks like Cowboy closes the connection before the Load Balancer does. The Load Balancer sends requests to a closed connection.
Better explained [here](https://blog.percy.io/tuning-nginx-behind-google-cloud-platform-http-s-load-balancer-305982ddb340) .
The solution for nginx is to set the `keepalive_timeout` to a bigger time than the Load Balancer.
Any Idea how to do it with Cowboy?.

Thanks in advance.

My current version is 1.1.2
With phoenix 1.3.2

**Comment by essen** [comment]
In the first version of Cowboy it was a protocol option called `timeout` and it defaults to 5000ms.

**Comment by arturictus** [comment]
@essen thanks for the fast response.
I've tried to set this option via phoenix config without luck.
I know is not is no related to this library but wouldn't you know how to pass the config from phoenix?.
I've tried:

```elixir
config :my_app, MyApp.Endpoint,
  http: [port: {:system, "PORT"}, timeout: 30_000],
  #...
```

```elixir
config :my_app, MyApp.Endpoint,
  http: [port: {:system, "PORT"}, protocol_options: [timeout: 30_000]],
  #...
```

```elixir
config :my_app, MyApp.Endpoint,
  http: [port: {:system, "PORT"},cowboy: [timeout: 30_000]],
  #...
```

**Comment by Gazler** [comment]
@arturictus The first option is the correct one. It is passed to ranch using https://github.com/elixir-plug/plug/blob/v1.5.0/lib/plug/adapters/cowboy.ex#L137

**Comment by essen** [comment]
Try the correct option with wireshark or other to see what's happening. Just telnet would be good enough to confirm the timeout is used as expected.

**Comment by arturictus** [comment]
The setup for Google Cloud Load Balancer should be:
```elixir
config :my_app, MyApp.Endpoint,
  http: [port: {:system, "PORT"},
         timeout: 30_000,
         protocol_options: [max_keepalive: 10_000]],
  #...
```
I hope that helps

**Comment by michaelst** [comment]
@arturictus Google specifies in their docs that it should be set greater than 600 seconds for the keepalive, is there a reason why you say it should be 10 seconds https://cloud.google.com/load-balancing/docs/https/#timeouts_and_retries

**Comment by arturictus** [comment]
Hi @michaelst ,
https://ninenines.eu/docs/en/cowboy/1.0/guide/http_req_life/
> Cowboy will only accept a certain number of new requests on the same connection. By default it will run up to 100 requests. This number can be changed by setting the max_keepalive configuration value when starting an HTTP listener.

but you are right, I should bump the timeout to 600_000
corrected setup:

```elixir
config :my_app, MyApp.Endpoint,
  http: [port: {:system, "PORT"},
         timeout: 605_000,
         protocol_options: [max_keepalive: 10_000]],
  #...
```

**Comment by michaelst** [comment]
That is incorrect also as it is not the timeout but the keepalive. These are the settings that finally stopped the 502 errors for us 
```
  https: [
    port: 443,
    timeout: 30_000,
    protocol_options: [max_keepalive: 600_001],
  ],

**Comment by arturictus** [comment]
Hi @michaelst,
I really don't get it how.
The google documentation says:
-  TCP session timeout, whose value is fixed at 10 minutes (600 seconds)

The cowboy documentation says about `max_keepalive`:
- https://ninenines.eu/docs/en/cowboy/1.0/manual/cowboy_protocol/
  Maximum number of requests allowed per connection.

This comes from Plug.Adapter.Cowboy: https://hexdocs.pm/plug/Plug.Adapters.Cowboy.html

How number of request affect to the timeout?

**Comment by michaelst** [comment]
I was reading the settings as max_keepalive being the keepalive timeout for a connection and timeout being for an individual request. It also appears to behave this way as we have not had any 502 errors since changing to the configuration I posted where we did have 502 errors with your revised configuration. I need to look into the documentation some more to see what is happening.

> A TCP session timeout, whose value is fixed at 10 minutes (600 seconds). This session timeout is sometimes called a keepalive or idle timeout

**Comment by essen** [comment]
`max_keepalive` is not a timeout, it's the max number of requests on the same connection using the keepalive mechanism. It's possible you get 502s both when Cowboy timeouts and when Cowboy closes the connection when that number is reached though. I suppose `infinity` would be a better value for it in that case.

**Comment by rhysldavis** [comment]
Any further progress on this issue, trying to solve it myself for GCP and it seems like setting max_keepalive to 600_001 is a bandaid until you have that number of user requests in 10 minute intervals?

**Comment by essen** [comment]
There's no issue as far as I can tell.

**Comment by taylordowns2000** [comment]
Hi all, I don't think there's an issue—maybe a lack of documentation? This one is still giving me headaches, and I think it's terminology related. As @michaelst points out on the GCP Kubernetes docs:

"""
A TCP session timeout, whose value is fixed at 10 minutes (600 seconds). This session timeout is sometimes called a keepalive or idle timeout, and its value is not configurable by modifying your backend service. You must configure the web server software used by your backends so that its keepalive timeout is longer than 600 seconds to prevent connections from being closed prematurely by the backend. This timeout does not apply to WebSockets.
"""

If I'm reading that right, and looking through the docs here (https://ninenines.eu/docs/en/cowboy/2.8/manual/cowboy_http/), I think the key setting is `idle_timeout`, and not `timeout`. I'm trying this:
```ex
config :my_ap, MyAppWeb.Endpoint,
  http: [
    protocol_options: [
      # https://ninenines.eu/docs/en/cowboy/2.8/manual/cowboy_http/
      request_timeout: 30_000,
      # https://cloud.google.com/load-balancing/docs/https/#timeouts_and_retries
      idle_timeout: 650_000, # must be greater than 600s
      max_keepalive: :infinity
    ]
  ],
  render_errors: [accepts: ~w(html json)],
  pubsub_server: MyApp.PubSub
```
Will update here if it works.

Has anyone else solved this?

**Comment by essen** [comment]
`timeout` was in Cowboy 1.x, it's called `idle_timeout` now, so I think your configuration is correct.

**Comment by taylordowns2000** [comment]
Thank you! Yes, seems to be working for me, btw.

**Comment by jace-ys** [comment]
For anyone that comes across this, we've tried many variations of the above recommendations using `idle_timeout` but nothing worked for us as we were still seeing 502s with `backend_connection_closed_before_data_sent_to_client`.

The magic sauce was `request_timeout` and I think this comment captures the crux of the issue: https://github.com/ninenines/cowboy/blob/24d32de931a0c985ff7939077463fc8be939f0e9/src/cowboy_http.erl#L295-L311

Essentially, `request_timeout` is the timeout that closes connections between requests from the persistent load balancer connection, whereas `idle_timeout` is the timeout that closes connections during an idle (pipelined) request.
